### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by afk-olkie** [bminer/intel-hex.js#3]
When working with ARM processor hex dumps, the file will often start from something like 0x8000000 instead of 0. The current library tries to fill address space from 0x0 to 0x8000000.

This results in the following error:
```
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
```

Example file start:
```
:020000040800F2
:200000000000000000000000000000000000000000000000000000000000000000000000E0
...
```

**Comment by bminer** [comment]
Eww... good to know.  Any thoughts on how to fix?  I presume that happens here: https://github.com/bminer/intel-hex.js/blob/master/index.js#L77 ???

**Comment by afk-olkie** [comment]
Yeah that is where it happens. There are lots of ways you could fix. The lowest effort method would be to copy what the python intelhex lib does which is return a dictionary of address as key and value. You could use the js Map class.

**Comment by bminer** [comment]
Here's the thing... in the end, I really want empty space to be padded with 0xFF or 0.  So if the Intel hex file address starts with 0x8000000, this library is designed to return the first 128MiB filled with 0xFF.

The [approach](http://srecord.sourceforge.net/man/man5/srec_binary.html) taken by [`srecord`](http://srecord.sourceforge.net) when writing binary files is to add [file holes](https://en.wikipedia.org/wiki/Sparse_file).  There's no way to do that AFAIK here.

**Comment by bminer** [comment]
I'm going to close this issue for now because I think that the current behavior is correct.  Intel Hex formats provide support for jumping around in the address space, but I believe that the binary format should represent the entire address space.  Please feel free to continue the discussion, though!

**Comment by afk-olkie** [comment]
I'm not sure I understand why you want to try and store bytes that are not present in the source hex file. Giving them a value of 0xFF or 0x00 is misleading. We have no idea what the values are because they aren't in the source hex file. You could however use an "unread" value of 0xFFFF or something out of normal range.

I don't think the issue is a shortage of ram. What if my file started near the end of the 32 bit address space? Should my program really need gigs and gigs of RAM to parse a 64 KB file? This is just the reality of the design.

I'm also not trying to convince you to change your implementation. It would take a lot of refactoring and there is already a good looking alternative that uses an efficient hybrid approach: https://github.com/NordicSemiconductor/nrf-intel-hex

That said, it would be cool if you could add a quick note in the readme to help future users determine if your lib will meet their needs.

**Comment by bminer** [comment]
You make a lot of good points.  To be honest, I'm **not** an expert on this, so take all of this with a grain of salt.

> Should my program really need gigs and gigs of RAM to parse a 64 KB file?

I think that the answer is *mostly* yes.  If the file started near the end of the 32-bit address space, how do you create a binary representation of that file?  In Intel Hex format, you can specify a starting address for a block of data, but in a raw binary file output, you can't.  The raw binary file really needs to represent the contents of memory... so in this case, the file could be as large as 4 GiB.  That's where [sparse files](https://en.wikipedia.org/wiki/Sparse_file) might come into play so that gigabytes of *actual* disk space aren't wasted by a mostly empty file.  As I mentioned before, I could revise this lib to write to disk via streams instead of allocating a buffer in RAM and running out of memory.

Also, as you probably know, it is common to use 0xFF or 0x00 for each "empty" portion of the file, as it is common for microcontrollers to consider these bytes as invalid instructions.

I also could have written the parser to spit out address offsets and corresponding Buffers for contiguous data blocks, but this lib is simple and only outputs a single Buffer of binary data.  :-/  I will certainly consider updating the README to clarify this fact.  Or, I would certainly consider PRs to provide this additional functionality.

**Comment by afk-olkie** [comment]
I'm not sure I can explain this many other ways, but thank you for the discussion.

In many cases, the address space of smaller microcontrollers has large totally useless sections that can't be read, or are used for many things other than FLASH or RAM like peripherals, bit banding, control registers... the address space is shared by many many things. Requiring that they all be read together or not at all is kind of like having to empty the entire fridge just to get the oranges. Or showing up to the library with a million backpacks just to take one book home.

**Comment by bminer** [comment]
@afk-olkie - I know it's been years, but we have a proposed solution in PR #7.  If you're interested in helping this project and have extra time to review it, please let me know! Thanks!
